import { useEffect, useState } from 'react';
import { AlertTriangle, Clock } from 'lucide-react';
import { apiRequest } from '../services/api';
import { useSocket } from '../context/SocketContext';
import PageHeader from '../components/PageHeader';
import { getAccidentSeverity } from '../utils/severity';

export default function Alerts() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const { alerts: liveAlerts } = useSocket();
  const { liveData } = useSocket();

  useEffect(() => {
    const fetchAlerts = async () => {
      try {
        setAlerts(await apiRequest('/api/alerts'));
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchAlerts();
  }, []);

  useEffect(() => {
    if (!liveAlerts.length) return;

    setAlerts((current) => {
      const next = [...liveAlerts, ...current];
      const seen = new Set();
      return next.filter((item) => {
        if (seen.has(item.id)) return false;
        seen.add(item.id);
        return true;
      }).slice(0, 50);
    });
  }, [liveAlerts]);

  if (loading) return <div className="animate-pulse text-slate-400">Loading alerts...</div>;

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Response"
        title="Alert command queue"
        description="Monitor fall, drowsiness, alcohol, and low battery events as they are generated by the telemetry pipeline."
      />

      <div className="overflow-hidden rounded-[2rem] border border-slate-800 bg-slate-950">
        {alerts.length === 0 ? (
          <div className="p-12 text-center text-slate-400">
            <AlertTriangle className="mx-auto mb-4 text-emerald-500" size={48} />
            <p className="text-lg">No alerts found. Riders are safe.</p>
          </div>
        ) : (
          <ul className="divide-y divide-slate-800">
            {alerts.map((alert) => (
              <li key={alert.id} className="flex items-center justify-between p-6 transition-colors hover:bg-slate-900/60">
                <div className="flex items-start gap-4">
                  <div className="mt-1 rounded-full bg-red-900/30 p-3">
                    <AlertTriangle className="text-red-500" size={20} />
                  </div>
                  <div>
                    <h3 className="mb-1 text-lg font-bold text-red-400">{alert.type.replaceAll('_', ' ')}</h3>
                    <p className="text-sm text-slate-400">{alert.message}</p>
                    <p className="mt-1 text-sm text-slate-500">Helmet ID: <span className="font-mono text-slate-300">{alert.helmet_id}</span></p>
                    {alert.type === 'FALL_DETECTED' ? (
                      <div className="mt-2 rounded-2xl border border-rose-500/20 bg-rose-500/10 p-3 text-sm text-rose-100">
                        <p>Severity Level: {getAccidentSeverity(liveData || {}).level || 3}</p>
                        <p>Location: {liveData?.latitude ?? '--'}, {liveData?.longitude ?? '--'}</p>
                        <p>SMS sent to:</p>
                        <p>• Emergency Contact</p>
                        <p>• Ambulance Service (108)</p>
                      </div>
                    ) : null}
                    <p className="mt-1 flex items-center gap-1 text-sm text-slate-500">
                      <Clock size={14} /> {new Date(alert.timestamp).toLocaleString()}
                    </p>
                  </div>
                </div>
                <div className="hidden sm:block">
                  <span className="rounded-full border border-red-500/20 bg-red-500/10 px-3 py-1 text-xs font-bold uppercase tracking-wider text-red-500">
                    {alert.severity}
                  </span>
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
